### ISSUE TITLE
Naming the Data Transformers

### ISSUE THREAD

**Issue by ohare93** [ohare93/Vocab-Flashcards-Manager#1]
I have tried to draw the setup I have, and detail the naming issues I am facing.

![image](https://user-images.githubusercontent.com/1471350/66289336-a75f4a80-e8dc-11e9-8730-be9c5da4e44a.png)
![image](https://user-images.githubusercontent.com/1471350/66289338-a9c1a480-e8dc-11e9-91cf-42ebdd2a8420.png)
![image](https://user-images.githubusercontent.com/1471350/66289341-ab8b6800-e8dc-11e9-8ec6-062414f73c7b.png)

These config files that lie in between Deck Parts and everything else detail how the data transformation should occur, and can be done in either direction.

I am open to the idea of CrowdAnki json just being another "Source Type", and merging these into one concept. The only thing stopping me from doing that was that CrowdAnki json files read from/write to all 3 deck part types, rather than just one. 

*And regardless* what do I call the Config files? 😭

**Comment by ohare93** [comment]
@cofinley pls help

**Comment by cofinley** [comment]
You could call them "mappings" perhaps. "Transformers" fits too, from what I understand. You're not alone in finding this difficult:
> There are only two hard things in Computer Science: cache invalidation and naming things.
>
>  \- Phil Karlton

But finding the perfect name isn't as important as making sure the thing you are trying to name has a well-defined scope of functionality. In other words, as long as *you* know what they do and can explain it, that can suffice for now. You can always rename them later. Perhaps by working with them more, a proper name will reveal itself.
